### ISSUE TITLE
Proteogenomics analysis of label-free MS/MS data

### ISSUE THREAD

**Issue by okendojo** [wenbostar/PGA#12]
Hi,

I have a raw msms data and I would like to do proteogenomics analysis on them. The reason for writing is to request for a complete workflow of this wonderful package.

Thanks and I look forward to hear from you. My email address is oknjav001@myuct.ac.za

**Comment by wenbostar** [comment]
What type of novel peptides do you want to identify?

Bo

**Comment by okendojo** [comment]
Okay I have an MS/MS raw data (LFQ) from the and I want to determine the novel peprides and the SNPs from this data.

**Comment by wenbostar** [comment]
You can follow this tutorial: http://bioconductor.org/packages/devel/bioc/vignettes/PGA/inst/doc/PGA.pdf. Please feel free to let me know if you have any questions when you use these functions.

Bo
