### ISSUE TITLE
rTANDEM is unavailable

### ISSUE THREAD

**Issue by zhangyimin40** [wenbostar/PGA#25]
Hi,

I failed to install PGA as rTANDEM has been removed from bioconductor, could you please let me know the solution?

> Bioconductor version 3.12 (BiocManager 1.30.16), R 4.0.4 (2021-02-15)
> Installing package(s) 'rTANDEM'
> package �rTANDEM� is not available for Bioconductor version '3.12'

Thanks

**Comment by wenbostar** [comment]
You could use an older version of Bioconductor as shown here: https://github.com/wenbostar/PGA/blob/docker/Dockerfile.

In addition, you could use our prebuilt docker of PGA: docker pull proteomics/pga

**Comment by zhangyimin40** [comment]
Thanks Bo, it's resolved!

**Comment by BenSamy2020** [comment]
Greetings @wenbostar,

I came across this extremely useful package of yours. Unfortunately, I am facing this similar issue. So I performed the docker pull proteomics/pga command and successfully installed it. I am extremely new to command line. **By any chance do you have a guide on how to run this program using docker? Additionally, how do you integrate RStudio into this environment for usage?**

Regards,
Ben

**Comment by wenbostar** [comment]
Could you open a new issue and describe what function in PGA you want to use?

**Comment by BenSamy2020** [comment]
Greetings @wenbostar,

My apologies for the inconvenience caused. I have created a new issue.

Regards,
Ben

**Comment by wenbostar** [comment]
#26
