### ISSUE TITLE
PrepareAnnotationRefseq2 error

### ISSUE THREAD

**Issue by jaya-share** [wenbostar/PGA#3]
Faced error while executing command on
R version 3.4.4
customProDB_1.18.0, PGA_1.8.1
Command executed from tutorial
```r
transcript_ids <- c("NM_001126112", "NM_033360", "NR_073499")
pepfasta <- system.file("extdata", "refseq_pro_seq.fasta",
                        package="customProDB")
CDSfasta <- system.file("extdata", "refseq_coding_seq.fasta",
                        package="customProDB")
annotation_path <- tempdir()
PrepareAnnotationRefseq2(genome='hg19', CDSfasta, pepfasta, annotation_path,
                          dbsnp=NULL, transcript_ids=transcript_ids,
                          splice_matrix=FALSE, COSMIC=FALSE)
```
Build TranscriptDB object (txdb.sqlite) ... 
Error in .tablename2track(tablename, session) : 
  UCSC table "refGene" is not supported

**Comment by wenbostar** [comment]
Please use the latest version of PGA in this repository: [PGA](https://github.com/Shawn-Xu/PGA). We just fixed a few bugs which were caused by the changes of UCSC annotation. Please install the new version using the following code:
```r
install.packages("BiocManager")
BiocManager::install(version = '3.8')
install.package("RMariaDB")
library("BiocManager")
install("Shawn-Xu/PGA")
```

**Comment by jaya-share** [comment]
Thanks for the update..it seem to work now!

**Comment by wenbostar** [comment]
Great.
